import userIcon1 from "../assets/images/female_fighter_1.jpg";
import userIcon2 from "../assets/images/female_fighter_2.jpg";
import userIcon3 from "../assets/images/fighter_staring_0.jpg";
import userIcon4 from "../assets/images/fighter_staring_1.jpg";

export const mockRankingProfile = [
    {
        _id: "1",
        name: "Jan K",
        type: "Master",
        class: "45 Kg",
        country: "Philippines",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon1,
    },
    {
        _id: "2",
        name: "Hoa P",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon2,
    },
    {
        _id: "3",
        name: "Lo T",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon3,
    },
    {
        _id: "4",
        name: "Binh P",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon4,
    },
    {
        _id: "5",
        name: "Toan D",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon1,
    },
    {
        _id: "6",
        name: "Jan K",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon2,
    },
    {
        _id: "7",
        name: "Hoa P",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon2,
    },
    {
        _id: "8",
        name: "Lo T",
        type: "Master",
        class: "45 Kg",
        country: "Vietnam",
        recentFightOne: "1",
        recentFightTwo: "1",
        recentFightThree: "1",
        socialMedia: "X",
        icon: userIcon2,
    },
];
